pages/inspect.tsx
=> Add address in URL on input

components/NavBar/NavBar.tsx, pages/getData.tsx, utils/web3.ts
=> Add getData

pages/getData.tsx, pages/inspect.tsx, styles/globals.scss
Remove MUI TextField and Share button
=> Minor UI improvements

pages/getData.tsx
Add a drop down list of ERC725Y data keys in the page for `getData(...)`
See screenshot below.
closes #18
=> add dropdown list of some ERC725Y data keys

pages/getData.tsx
=> Add vault key to getData page

interfaces/interface_ids.ts, pages/inspect.tsx, utils/web3.ts
This PR checks for the interface id of the LSP contracts and displays if the address is a valid LSP contract.
UniversalProfile: `0x940EAC4bE26A42884883A79b6ee7179a24c42792`
LSP6KeyManager: `0x75b0B516B47A27b1819D21B26203Abf314d42CCE`
LSP1UniversalReceiverDelegateUP: `0x906B067e392e2c5f9E4f101f36C0b8CdA4885EBf`
LSP1UniversalReceiverDelegateVault: `0xDf951d2061b12922BFbF22cb17B17f3b39183570`
LSP7Mintable: `0xe14058B1c3def306e2cb37535647A04De03Db092`
LSP8Mintable: `0xF5b81Fe0B6F378f9E6A3fb6A6cD1921FCeA11799`
LSP9Vault: `0x67baFF31318638F497f4c4894Cd73918563942c8`
UniversalProfileInit: `0x6533158b042775e2FdFeF3cA1a782EFDbB8EB9b1`
LSP6KeyManagerInit: `0x73C68f1f41e4890D06Ba3e71b9E9DfA555f1fb46`
LSP7MintableInit: `0xD2D5e508C82EFc205cAFA4Ad969a4395Babce026`
LSP8MintableInit: …
=> feat: Check the interface ids of the LSPs on the inspect page.

components/UPOwner/UPOwner.tsx, components/UPOwner/index.ts, constants.ts, package-lock.json, package.json, pages/inspect.tsx, tsconfig.json
=> Add UP owner info to Inspect page

components/NavBar/NavBar.tsx, components/NavBar/components/NetworksSwitch/NetworksSwitch.tsx
=> Add link to test dapp in navbar

.eslintrc.json, components/KeyManagerPermissions/KeyManagerPermissions.tsx, components/UPOwner/UPOwner.tsx, package-lock.json, package.json, pages/inspect.tsx, utils/web3.ts
https://app.clickup.com/t/860q209t3
=> feat: supports lsp 0.8.+ contracts

package-lock.json, package.json
To be merged after relayer and extension are released
=> Update lsp to 0.11.1

components/HomeCards/CardContainer.tsx, components/HomeCards/HomeCard.tsx, components/HomeCards/components/HomeCard.tsx, components/HomeCards/index.ts, components/NavBar/NavBar.tsx, pages/index.tsx, styles/globals.scss
This PR updates the landing page for better navigation and clarity for external sources.
- Added `HomeCard` component for unified arrangement, animation, and styling
- Added `CardContainer` component for automated `HomeCard` generation 
- Added sticky header
- Removed external dApp from navigation bar
- Integrated version numbers and put tools into the _external developer resource_ section
=> Update landing page

components/AddressButtons/AddressButtons.tsx, components/DataKeysTable/DataKeysTable.tsx, components/Decode/Decode.module.scss, components/Decode/Decode.tsx, components/Encode/Encode.module.scss, components/Encode/Encode.tsx, components/Encode/components/EncodeExecute.module.scss, components/Encode/components/EncodeExecute.tsx, components/Encode/components/EncodeSetData.module.scss, components/Encode/components/EncodeSetData.tsx, components/Encode/components/EncodeTransferOwnership.module.scss, components/Encode/components/EncodeTransferOwnership.tsx, components/Encode/components/EncodedPayload.module.scss, components/Encode/components/EncodedPayload.tsx, components/ErrorMessage/ErrorMessage.tsx, components/UPOwner/UPOwner.tsx, package-lock.json, package.json, pages/_app.tsx, pages/abi-encoder.tsx, pages/abi-endoder.module.scss
This PR **removes all Material UI dependencies**
Instead, we use:
- **Style Modules** for each component
- Global **Bulma** classes
- No styling overwrites
- Better maintainability
- Improved clarity on elements
- Reduced storage
=> Remove Material UI

components/Decode/Decode.tsx, components/Encode/Encode.tsx, components/Encode/components/EncodeSetData.tsx, pages/abi-encoder.tsx, pages/abi-endoder.module.scss, styles/globals.scss
This PR introduces **updated headings, notes, links, and description**
- Added external links for every transaction type
=> ABI Encoder Redesign

pages/data-fetcher.tsx, styles/globals.scss
This PR introduces **updated headings, notes, links, and description**
- **Fixed** the default value of the menu bar input
- Cleaned the select dropdown to only feature the data keys
=> Data Fetcher Redesign + Input Fixes

components/Lsp2Coder/Lsp2Coder.tsx
This PR introduces **updated headings, links, and description**
=> LSP2 Encoder Added Links & Description

components/KeyManagerPermissions/KeyManagerPermissions.tsx, package-lock.json, package.json
Add ERC4337 in permission list
=> add button for `ERC4337_PERMISSION`

components/ValueTypeDecoder/ValueTypeDecoder.tsx, pages/inspector.tsx, utils/web3.ts
=> feat: add name of LSP4 Token type + Smart Contract version

components/ValueTypeDecoder/ValueTypeDecoder.tsx
=> feat: show number of elements as number for `Array` data keys

components/NavBar/components/NetworksSwitch/NetworksSwitch.tsx, globals.ts, pages/inspector.tsx, types/network.ts
This allows to debug local contract on local hardhat, etc.
=> Add localhost

components/ControllersList/ControllersList.tsx, components/ControllersList/index.ts, components/ValueTypeDecoder/ValueTypeDecoder.tsx, package-lock.json, package.json
=> feat: display list of permissions next to each controller

constants.ts, package-lock.json, package.json, utils/web3.ts
=> Decode metadata of tokens deployed with old + new interface ID

components/AddressInfos/AddressInfos.tsx, components/ControllersList/ControllersList.tsx, components/ValueTypeDecoder/ValueTypeDecoder.tsx, package-lock.json
I added the count of the balance for assets in the inspector, received assets array.
=> DEV-10824 Adding asset balance in inspector --> LSP5ReceivedAssets

components/ControllersList/ControllersList.tsx, components/ValueTypeDecoder/ValueTypeDecoder.tsx
=> refactor: convert `AddressPermissions[]` results into a table with individual Array data key indexes

pages/data-fetcher.tsx
=> feat: display both encoded + decoded value for Data Fetcher

components/CustomKeySchemaForm/CustomKeySchemaForm.tsx, pages/data-fetcher.tsx
This PR fixes the input change bug and adds a feature to custom key form to accept whole json
=> fix: data fetcher + custom key reading + json input

components/CustomKeySchemaForm/CustomKeySchemaForm.tsx, components/DataKeyBox/DataKeyBox.tsx, components/KeyManagerNonceChecker/KeyManagerNonceChecker.tsx, components/Lsp2Coder/Lsp2Coder.tsx, constants.ts, globals.ts, pages/data-fetcher.tsx, pages/inspector.tsx
Also gathered some LSP2 specs links together
=> Fix Custom Key Reading not working on initial click

README.md, components/ContractOwner/ContractOwner.tsx, components/DataKeyBox/schemas.ts, components/KeyManagerNonceChecker/KeyManagerNonceChecker.tsx, components/KeyManagerPermissions/KeyManagerPermissions.tsx, components/Lsp2Coder/Lsp2Coder.tsx, pages/abi-encoder.tsx, pages/data-fetcher.tsx, pages/index.tsx, pages/inspector.tsx
=> Fix broken links
